# Generated by Django 3.2.4 on 2021-07-07 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('idDocente', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.CharField(max_length=50, verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'docente',
                'verbose_name_plural': 'docentes',
                'ordering': ['docente'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idCurso', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('precio', models.IntegerField(verbose_name='Precio Unitario')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos', verbose_name='Imagen')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.docente')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['descripcion'],
            },
        ),
    ]
